<a href="https://colab.research.google.com/github/zacksmack/Data-Analytics-Bootcamp/blob/main/Python_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python


In [ ]:
c = 3
e = [7, 0, 3]
for count in range(0, 3):
	c = 5+c
print(c)

18


#Numpy


In [ ]:
np.arange(10
          )

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array([i for i in range(10,110,10)])

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.array(5)

array(5)

In [ ]:
np.array([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr=np.array(["fee","fi","fo", "f"])
arr[2].dtype


In [ ]:
arr=np.array([chr(i) for i in range (ord('A'),ord("Z")+5)])
arr

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', '\\', ']', '^'], dtype='<U1')

In [ ]:
bdf=np.zeros(10)
df.dtype

dtype('float64')

In [ ]:
np.random.randint(1,9,10)

array([4, 8, 8, 2, 4, 7, 5, 8, 8, 6])

In [ ]:
np.random.normal(5,1,10)

array([4.1556233 , 6.19344895, 6.05257416, 5.09919822, 5.26720566,
       5.08245123, 3.87015231, 4.75194762, 6.25718553, 6.50653722])

In [ ]:
np.random.rand(10)

array([0.86700796, 0.07599988, 0.20053996, 0.86925307, 0.59301779,
       0.367976  , 0.09917634, 0.24511705, 0.36349167, 0.29917695])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
print(np.zeros((10,10)))

print(np.ones(10))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
my_array=np.arange(1,13).reshape(3,4)
my_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
my_array[0,0]

1

In [ ]:
my_array.ndim

2

In [ ]:
arr

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', '\\', ']', '^'], dtype='<U1')

In [ ]:
my_array.shape

(3, 3)

In [ ]:
my_array.reshape(3,4)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
my_array.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x=my_array
x[0,0]=42
x

array([[42,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
y=np.random.randint(1,11,(3,4))
#or
z=np.random.randint(1,11,12).reshape(3,4)
y
z

array([[9, 4, 8, 1],
       [3, 8, 1, 3],
       [3, 3, 4, 1]])

In [ ]:
arr=np.random.randint(1,11,12).reshape(3,4)
arr

array([[8, 3, 7, 3],
       [2, 6, 1, 4],
       [3, 8, 3, 8]])

In [ ]:
arr-arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
z_list = [z for z in range(0,5)]
y_list = [z_list for y in range(0,4)]
x_list = [y_list for x in range(0,3)]
x_array=np.array(x_list)
x_array





array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [ ]:
z_list = [z for z in range(0,5)]
y_list = [z_list for y in range(0,4)]
x_list = [y_list for x in range(0,3)]

x_array = np.array(x_list)

x_array.shape


(3, 4, 5)

In [ ]:
x_array.ndim

3

In [ ]:
arr=np.arange(0,6).reshape(2,3)
arr.transpose()


array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
you=np.arange(0,20).reshape(5,4)
you

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
you.T[0]

array([ 0,  4,  8, 12, 16])

In [ ]:
you[-1]

array([16, 17, 18, 19])

In [ ]:
you[:,0]

array([ 0,  4,  8, 12, 16])

In [ ]:
you[0,:]

array([0, 1, 2, 3])

In [ ]:
you[0]

array([0, 1, 2, 3])

In [ ]:
you[:,2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18]])

In [ ]:
you[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

#Pandas

In [ ]:

import pandas as pd

In [ ]:

print(pd.__version__)

2.0.3


In [ ]:
given_list=[2,4,5,6,9]
series=pd.Series(given_list)
print(series)

0    2
1    4
2    5
3    6
4    9
dtype: int64


In [ ]:
series=pd.Series(given_list,index=[1,3,5,7,9])
print(series)

1    2
3    4
5    5
7    6
9    9
dtype: int64


In [ ]:
date_series=pd.date_range(start="05-01-2021", end="05-12-2021")
print(date_series)

DatetimeIndex(['2021-05-01', '2021-05-02', '2021-05-03', '2021-05-04',
               '2021-05-05', '2021-05-06', '2021-05-07', '2021-05-08',
               '2021-05-09', '2021-05-10', '2021-05-11', '2021-05-12'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
#f(x)=x/2
series=pd.Series([2,4,6,8,10], index=[1,2,3,4,5])
print(series)
print()
modified_series=series.apply(lambda x:x/2)
print(modified_series)

1     2
2     4
3     6
4     8
5    10
dtype: int64

1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float64


In [ ]:
dictionary={'name':['Vinay','Kushal','Aman'],
            'age' : [22,25,24],
            'occ': ['engineer','doctor','accountant']}
df=pd.DataFrame(dictionary)
print(df)

     name  age         occ
0   Vinay   22    engineer
1  Kushal   25      doctor
2    Aman   24  accountant


In [ ]:
list=[[2,'vishal',22],
      [1,'Kushal', 25],
      [1,'Aman',24]]
dataf= pd.DataFrame(list,columns=['id','name','age'],)
print(dataf)

   id    name  age
0   2  vishal   22
1   1  Kushal   25
2   1    Aman   24


In [ ]:
dataframe=pd.read_csv('/content/sample_data/mnist_test.csv')
print(dataframe)

In [ ]:
datatuto=[[1,'Vinay',22,'engineer'],
          [2,'Kushal',25,'doctor'],
          [3,'Aman',24,'accountant']]
datatuto_2=pd.DataFrame(datatuto,columns=['id','name','age','occ'],)
print(datatuto_2)


   id    name  age         occ
0   1   Vinay   22    engineer
1   2  Kushal   25      doctor
2   3    Aman   24  accountant


In [ ]:
print(datatuto_2)
print()
datatuto_2_sorted=datatuto_2.sort_values(by=['name'])
print(datatuto_2_sorted)

In [ ]:
print(datatuto_2)
print()
dataframe=datatuto_2.reset_index()
print(dataframe)

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [ ]:
print(dataframe)
print()
o=dataframe['name']
print(o)
print()
print(dataframe.loc[:,'name'])
print()
print(dataframe.iloc[:,1])

   index  id    name age         occ
0      0   1   Vinay  22    engineer
1      1   2  Kushal  25      doctor
2      2   3    Aman  24  accountant

0     Vinay
1    Kushal
2      Aman
Name: name, dtype: object

0     Vinay
1    Kushal
2      Aman
Name: name, dtype: object

0    1
1    2
2    3
Name: id, dtype: int64


In [ ]:
print(dataframe)
print()
print(dataframe.iloc[[0,1],:])
print()
print(dataframe.loc[[0,1],:])

   index  id    name age         occ
0      0   1   Vinay  22    engineer
1      1   2  Kushal  25      doctor
2      2   3    Aman  24  accountant

   index  id    name age       occ
0      0   1   Vinay  22  engineer
1      1   2  Kushal  25    doctor

   index  id    name age       occ
0      0   1   Vinay  22  engineer
1      1   2  Kushal  25    doctor


In [ ]:
print(dataframe)
print()
dataframe_condition=dataframe.loc[dataframe.age >= 24]
print(dataframe_condition)

   index  id    name  age         occ
0      0   1   Vinay   22    engineer
1      1   2  Kushal   25      doctor
2      2   3    Aman   24  accountant

   index  id    name  age         occ
1      1   2  Kushal   25      doctor
2      2   3    Aman   24  accountant


In [ ]:
dict3= {'name' : ['vinay', 'Kushal', 'Aman', 'Rahul', 'Ramsh'],
             'occ': ['engineer', 'doctor', 'engineer', 'doctor', 'doctor'],
             'salary': [60000, 70000, 50000, 60000, 65000]}
dataframe3=pd.DataFrame(dict3)
print(dataframe3)
print()
occ_average_age=dataframe3.groupby("occ")['salary'].mean()
print(occ_average_age)


     name       occ  salary
0   vinay  engineer   60000
1  Kushal    doctor   70000
2    Aman  engineer   50000
3   Rahul    doctor   60000
4   Ramsh    doctor   65000

occ
doctor      65000.0
engineer    55000.0
Name: salary, dtype: float64


#MATPLOTLIB

In [ ]:
x=np.arange(0,100)
y=x*2
z=x**2


<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>

#ML


In [ ]:
#link to future project : https://stackabuse.com/creating-a-neural-network-from-scratch-in-python/

In [ ]:
#First neural network with tensorflow
import tensorflow as tf
mnist=tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(10)
])
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(optimizer='adam', loss =loss, metrics =['accuracy'])
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test, y_test)


11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1875/1875 [==============================] - 13s 7ms/step - loss: 0.2581 - accuracy: 0.9268
Epoch 2/5
1875/1875 [==============================] - 15s 8ms/step - loss: 0.1160 - accuracy: 0.9660
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0800 - accuracy: 0.9760
Epoch 4/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0604 - accuracy: 0.9813
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0469 - accuracy: 0.9848


KeyboardInterrupt: 

In [ ]:
#Define Keras Model
model=Sequential()
model.add(Dense(12,input_shape=(8,),activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
#Prediction
predictions=model.predict(X)
rounded=[round(x[0]) for x in predictions]
predictions =(model.predict(X)>0.5).astype(int)
for i in range(5):
 print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))


24/24 [==============================] - 0s 6ms/step
[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] => 1 (expected 1)
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] => 0 (expected 0)
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] => 1 (expected 1)
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] => 0 (expected 0)
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] => 1 (expected 1)


<ipython-input-28-ea6e3abbf5e1>:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))


In [ ]:
#Link to article https://machinelearningmastery.com/tutorial-first-neural-network-python-keras/
# first neural network with keras make predictions
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
# load the dataset
dataset = loadtxt('pima-indians-diabetes.csv', delimiter=',')
# split into input (X) and output (y) variables
X = dataset[:,0:8]
y = dataset[:,8]
# define the keras model
model = Sequential()
model.add(Dense(12, input_shape=(8,), activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10, verbose=0)
# make class predictions with the model
predictions = (model.predict(X) > 0.5).astype(int)
# summarize the first 5 cases
for i in range(5):
	print('%s => %d (expected %d)' % (X[i].tolist(), predictions[i], y[i]))